[colors]
draw_bold_text_with_bright_colors = true

# Default colors theme OneDark - https://github.com/alacritty/alacritty-theme/blob/master/themes/one_dark.toml
[colors.primary]
background = '#2e3440'
foreground = '#d8dee9'
dim_foreground = '#a5abb6'

# Normal colors
[colors.normal]
black   = '#3b4252'
red     = '#bf616a'
green   = '#a3be8c'
yellow  = '#ebcb8b'
blue    = '#81a1c1'
magenta = '#b48ead'
cyan    = '#88c0d0'
white   = '#e5e9f0'

# Bright colors
[colors.bright]
black   = '#4c566a'
red     = '#bf616a'
green   = '#a3be8c'
yellow  = '#ebcb8b'
blue    = '#81a1c1'
magenta = '#b48ead'
cyan    = '#8fbcbb'
white   = '#eceff4'

# Dim colors
[colors.dim]
black   = "#373e4d"
red     = "#94545d"
green   = "#809575"
yellow  = "#b29e75"
blue    = "#68809a"
magenta = "#8c738c"
cyan    = "#6d96a5"
white   = "#aeb3bb"

[cursor]
blink_interval = 350

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 13.0

[font.bold]
family = "RecMonoDuotoneNerdFont"
style = "Bold"

[font.bold_italic]
family = "RecMonoDuotoneNerdFont"
style = "Bold Italic"

[font.italic]
family = "RecMonoDuotoneNerdFont"
style = "Italic"

[font.normal]
family = "RecMonoDuotoneNerdFont"
style = "Regular"

[scrolling]
history = 10000

[window]
#decorations = "full"
dynamic_title = true
opacity = 0.85
startup_mode = "Windowed"
#title = "Alacritty ~ Thiago Werminghoff"
